### ISSUE TITLE
Establishing a mode of communication

### ISSUE THREAD

**Issue by lewis-carson** [eti0/ricebowl#1]
Can someone start a damn IRC channel or something so we can communicate. I'd love to help but I don't know where to start.

**Comment by icyphox** [comment]
Uh, `#rice` on Rizon?

**Comment by icyphox** [comment]
Uh, #rice on Rizon?

**Comment by lewis-carson** [comment]
Eh, `#rice` isn't just for developing this.  We need one which is not filled with other people

**Comment by eti0** [comment]
@icyphox you ok?
@hexx112 we can use `#ricebowl` on Rizon i guess. not that it really matters.

**Comment by icyphox** [comment]
@eti0 shitty mobile data

**Comment by lewis-carson** [comment]
`#ricebowl` is free on freenode which is intended for foss devs

**Comment by eti0** [comment]
not really no. what's the issue with Rizon? We're not devs, this is something we're doing for fun really.  
may i ask what your IRC handle is?

**Comment by lewis-carson** [comment]
Me neither, I've just never used rizon. It's torvim, by the way

**Comment by eti0** [comment]
rizon is fine really. you can join `#rice` anytime if you want to discuss about this project.  
i'll join `#ricebowl` if talking in `#rice` really bothers you.
